### PR TITLE
Update kubetail.rb

### PR DESCRIPTION
**Pull request by naseemkullah**
Adding short name

### CODE REVIEW

**Comment by johanhaleby** [comment]
Cool stuff! This is great! However I still want to hear what your thoughts are on calling it `kt` instead of `ktail`? Is `kt` too short? Miss-leading?

**Comment by johanhaleby** [comment]
I've asked around at work and people here at least seem to favor `kt` over `ktail`. Also when I googled for `ktail` I found another project with that name so perhaps it's better if we don't clash.

**Comment by naseemkullah** [comment]
Very good point! `kt` it is, I changed it now.

**Comment by johanhaleby** [comment]
Thanks a ton! What about code completion? How do we fix that for `kt`?

**Comment by naseemkullah** [comment]
My absolute pleasure. I've made a PR for bash and zsh but not sure about fish :/

**Comment by johanhaleby** [comment]
@naseemkullah Thanks!!

**Pull request merged**
